### PR TITLE
Make Dialyzer happy

### PR DESCRIPTION
**Pull request by erszcz**
These changes lead to no errors/warning in Dialyzer output except some related to unused functions in `mock_http_server`. I guess these functions might be used someday, so didn't remove them.

Especially https://github.com/lavrin/wsecli/commit/b4603f5f74d44c48726dc875bc7b1019fda2c102 is important, because it (temporarily, I guess) fixes the problem I reported in https://github.com/madtrick/wsecli/issues/15.

My master branch contains a Makefile with Dialyzer setup I used.

### CODE REVIEW

**Comment by erszcz** [comment]
BTW, it would be great to have this tagged if you decide to merge. Rebar likes tags.

**Comment by madtrick** [comment]
Hi, I was on vacation these days and I couldn't take a look to your contributions. I hope this week I will be able to do it.

**Comment by madtrick** [comment]
Pushed with tag 1.1.0

Thankyou for your fixes : )

**Comment by erszcz** [comment]
Thanks for merging this stuff. One more thingy: could you make `wsecli` 1.1.0 (or 1.1.1, not to overwrite an already public tag) use `wsock` 1.1.5? This would allow me to refer just to `wsecli` in my `rebar.config`, but still have both of them fetched in Dialyzer friendly versions.

**Comment by madtrick** [comment]
S**t! you are right. I totally forgot to do that. Fixed and pushed with tag 1.1.1

BTW I included your `Makefile` in the project.

**Comment by erszcz** [comment]
Cool, thanks again!

**Pull request merged**
